### ISSUE TITLE
Header not lined up

### ISSUE THREAD

**Issue by moschel** [canjs/bit-docs-html-canjs#166]
![2016-10-25_2112](https://cloud.githubusercontent.com/assets/22180/19710970/e225696e-9af7-11e6-8af4-2ec8e0f19fd8.png)

The left part of the black bar in the header is higher than the right part.

**Comment by garrettreed** [comment]
Justification is fixed with a static height. Chrome still shows a discrepancy at 80% zoom (shown below) because of some weird calculation with inline-flex on the top-right nav. The computed heights are fine, but it's not rendered like with those numbers. I'll investigate further while browser testing.

![screen shot 2016-10-27 at 10 54 59 am](https://cloud.githubusercontent.com/assets/4079858/19772541/941dead2-9c34-11e6-9e1c-04fcdd839fed.png)
