### ISSUE TITLE
Review "show top navigation" design

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#171]
@garrettreed made this: https://github.com/canjs/bit-docs-html-canjs/pull/167

Please review and make any design improvements you think are necessary.

**Comment by tomgreever** [comment]
I think what @garrettreed implemented is fine, however, I don't think the "Back to top" arrow and scroll-to-top functionality is necessary. Why was it added? 

The reason I think it's not necessary is:
- There's nothing in the top (white) nav that the user will need b/c the main nav is on the left
- I think most people will be accustomed to scrolling back up to the top of the page if they need to
- The "On this page" menu can also help them move back to the top of the content.
- I don't think people expect websites to build in a "scroll back to top" feature, although it can be useful. In this case, I don't see the utility.

If we want to keep this functionality, I'd suggest: 
- using a different icon- the up arrow seems a little big and it doesn't have the same meaning as the others. The others mean "There is a menu here"
- putting the icon in a different place. The scroll to top + Bitovi menu opening is weird.

**Comment by garrettreed** [comment]
@tomgreever here's a demonstration of the utility:

1. Navigate to http://v3.canjs.com/doc/can-component.html
2. Scroll down enough so that the top nav is hidden.
3. Click the `tag` link in the sidebar.

Since the content is too short to create a scrollbar, you cannot scroll up to re-enable the top nav. The scroll-to-top arrow is the workaround for this.

We could alter this solution to only show the arrow on articles that don't scroll.

**Comment by tomgreever** [comment]
Thanks @garrettreed that's a good example. When I click on a new "page" I expect to be taken to the top of that page. This is how the majority of websites behave, because they're actually going to new pages. I realize this is not how SPAs behave by default, but I personally consider it to be a drawback of SPAs. 

So my suggested solution would be that if the user goes to a new "page" - we automatically take them to the top and reveal the nav for them. Is that sort of functionality possible? If so, I think it would solve for this - but not sure.

**Comment by garrettreed** [comment]
@tomgreever yes, that was the original behavior. @justinbmeyer requested it remain hidden through page changes until the user manually scrolls to the top. Implementing this revealed the problem of not being able to show the header on pages that cannot scroll. I could easily remove this feature if that's the route we want to go. I'll let Justin weigh in on it first.

**Comment by justinbmeyer** [comment]
Isn't there a button to show it? Yeah, I don't want the top to be visible once someone is "into the docs" because you almost never need to access it.

**Comment by tomgreever** [comment]
@justinbmeyer yes, there is a button. Clicking it takes the user back to the top of the page. My suggestion is to remove this button because it's not necessary. The user can scroll or use the "on this page" breadcrumb. 

In @garrettreed's example, I would suggest we still allow for scrolling. If the user scrolls up on a page that doesn't have enough content for scrolling - this scrolling triggers the reveal of the top/white nav. Is that possible?

**Comment by justinbmeyer** [comment]
Unfortunately, it's not easy, maybe possible. We'd have to render the content off-screen to get the dimensions and possibly add some padding to make it scrollable so we could actually get the scroll event.
