### ISSUE TITLE
Unnecessary line breaks in search results

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#351]
This search’s second and third results have line breaks that seem unnecessary:
<img width="303" alt="screen shot 2017-06-27 at 7 49 47 am" src="https://user-images.githubusercontent.com/10070176/27594094-c3f08f6a-5b0d-11e7-889f-dda4de58ff6f.png">

**Comment by imaustink** [comment]
Interesting. I already fixed this issue here: https://github.com/canjs/bit-docs-html-canjs/commit/ccef0045941a9cd675b2c1cc2af7fb5b7a454ba2#diff-c8f660620166214d09713b480364375dR87.

Also, I don't see this in master:
![screen shot 2017-06-27 at 10 02 50 am](https://user-images.githubusercontent.com/6282922/27600138-d3d29b46-5b1f-11e7-9ac2-e77ec6712ea6.png)

**Comment by chasenlehara** [comment]
I can reproduce this in `master`. Those links need to be `inline`, not `inline-block`, so they flow with the rest of the text.
