### ISSUE TITLE
outline should not include headings within signatures 

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#455]
Notice parameters:

![canjs_-_can-query-logic](https://user-images.githubusercontent.com/78602/38281994-3b4afd6a-3773-11e8-8930-055deea63eff.png)

This happens with `@outline 2`

**Comment by cherifGsoul** [comment]
Should we hide all sub-items like in the screenshot?
<img width="428" alt="Screen Shot 2019-06-06 at 2 07 12 PM" src="https://user-images.githubusercontent.com/109013/59035107-760a3b80-8864-11e9-837c-cb8c547d2914.png">

**Comment by chasenlehara** [comment]
No, the [can-query-logic](https://canjs.com/doc/can-query-logic.html) page should look like this:

<img width="492" alt="Screen Shot 2019-06-06 at 9 27 15 AM" src="https://user-images.githubusercontent.com/10070176/59049653-54498e00-883d-11e9-85c2-4f5c0ca9ccf4.png">

The TOC in the right sidebar should also be fixed:

<img width="319" alt="Screen Shot 2019-06-06 at 9 28 54 AM" src="https://user-images.githubusercontent.com/10070176/59049724-85c25980-883d-11e9-977c-6145e55cc4a1.png">

I think the sidebar TOC can be fixed in this file: https://github.com/bit-docs/bit-docs-html-toc/blob/master/toc-control.js
