### ISSUE TITLE
Very wide code doesn't create a horizontal scrollbar

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#74]
We should see a horizontal scrollbar here:

![canjs_github_io_canjs_doc_guides_chat_html_and_style__diff__code_view_ _issue__62_ _canjs_bit-docs-html-canjs](https://cloud.githubusercontent.com/assets/78602/18838698/f6a7a398-83cd-11e6-9b27-a62dd374e1e4.png)

**Comment by garrettreed** [comment]
The specified behavior was fixed with the introduction of the mobile layout. However, a related issue was introduced. While the `<pre>` blocks allow scrolling, the child `<code>` block only fills the parent container. This breaks the highlighting on scroll:

<img width="304" alt="screen shot 2016-10-11 at 2 35 50 pm" src="https://cloud.githubusercontent.com/assets/4079858/19284072/651f0c44-8fc2-11e6-8f14-a46e339fbddb.png">

A simple fix for this is floating the `<code>` block, but this extends the expander icons to the center, so they are not visible until scrolled. Is this acceptable behavior?

<img width="336" alt="screen shot 2016-10-11 at 2 52 06 pm" src="https://cloud.githubusercontent.com/assets/4079858/19284100/83d1a50c-8fc2-11e6-90a9-a290b1d3358e.png">

**Comment by justinbmeyer** [comment]
@garrettreed yeah, that's fine.  Thanks!
