### ISSUE TITLE
Demos are broken and unstyled

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#96]
> STATUS: Some styles fixed, but there's a problem where the active tab is not showing up as being active.

http://canjs.github.io/canjs/doc/can-stache-bindings.twoWay.html

![can-stache-bindings](https://cloud.githubusercontent.com/assets/78602/18997764/7f2ed2f6-86fb-11e6-9852-7e7e1b9f1181.png)

**Comment by garrettreed** [comment]
@andreaalmeida I thought I fixed this issue here: https://github.com/canjs/bit-docs-html-canjs/issues/49. I figured the problem was that `demo.less` wasn't being added. Now that it is, the styles are still not correct, so I'm guessing the content in `demo.less` needs to be updated.

The tough part about this one is that the demos are not available in bit-docs-html-canjs.

**Comment by justinbmeyer** [comment]
There's still a problem that the tabs are not shown as being selected:

<img width="636" alt="can-component" src="https://cloud.githubusercontent.com/assets/78602/19018052/f9e3e004-8818-11e6-822e-e268b1923352.png">
